`require "action_dispatch"` to use Mime::Type
This fix the following error:
```
ActionView::Template::Error: undefined method `to_sym' for nil:NilClass

          @symbol = symbol.to_sym
                          ^^^^^^^
```